# Generated by Django 3.2.4 on 2021-07-28 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='sqrt',
            new_name='sqft',
        ),
    ]
